using Sandlada.Extension.Auth.Domain.Commons;
using Sandlada.Extension.Auth.Domain.Primitives;
using Sandlada.Extension.Auth.Domain.ValueObjects;

namespace Sandlada.Extension.Auth.Domain.Aggregates;

public sealed record UserConstructorArgs {
    public required Guid Id { get; init; }
    public required EmailAddress EmailAddress { get; init; }
    public required string? UniqueName { get; init; }
    public required UserRole Role { get; init; }
    public required string PasswordHash { get; init; }
    public required bool IsEmailVerified { get; init; }
    public DateTime? FirstLoginAt { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required DateTime UpdatedAt { get; init; }
    public UserStatus Status { get; init; } = UserStatus.Enabled;
}

public sealed class User : IAggregate<Guid> {

    #region Properties

    /// <summary>
    /// Id is the unique identifier of the user.
    /// It is generated by the system and cannot be changed.
    /// It is used as the primary key in the database and as the identifier in the application.
    /// Only visible to the user themselves and administrators. It is not used for login or display purposes.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// EmailAddress is the email address of the user. It must be unique across all users.
    /// It is used for login and communication purposes.
    /// </summary>
    public EmailAddress EmailAddress { get; private set; } = default!;

    /// <summary>
    /// IsEmailVerified indicates whether the user's email address has been verified. This is important for security and communication purposes.
    /// If the email address is not verified, the user may have limited access to certain features or may be required to verify their email before they can use the application fully.
    /// </summary>
    public bool IsEmailVerified { get; private set; }

    /// <summary>
    /// UniqueName is a unique identifier for the user that can be used for login and display purposes.
    /// It must be unique across all users once set. It can be changed.
    /// It can be used as '@UniqueName' to mention the user in conversations. It can also be used as part of the user's profile URL, e.g. '/users/UniqueName'.
    /// </summary>
    public string? UniqueName { get; private set; }

    /// <summary>
    /// Status determines the user's current state within the application.
    /// Possible values: Enabled, Disabled, Suspended, Blocked, Deleted.
    /// Default is Enabled for newly created users.
    /// The status can be changed by an administrator.
    /// </summary>
    public UserStatus Status { get; private set; } = UserStatus.Enabled;

    /// <summary>
    /// New users are assigned the "normal" role by default.
    /// The role determines the user's permissions and access levels within the application.
    /// The system may have different roles such as "administrator", "normal"
    /// The role can be changed by an administrator or through specific actions within the application, such as upgrading to a premium account.
    /// </summary>
    public UserRole Role { get; private set; } = UserRole.Normal;
    public string PasswordHash { get; private set; } = string.Empty;
    public DateTime? FirstLoginAt { get; private set; }

    public DateTime CreatedAt { get; private set; } = DateTime.UnixEpoch;
    public DateTime UpdatedAt { get; private set; } = DateTime.UnixEpoch;
    #endregion

    #region Constructors
    private User() {
    }
    private User(UserConstructorArgs args) {
        this.Id              = args.Id;
        this.EmailAddress    = args.EmailAddress;
        this.UniqueName      = args.UniqueName;
        this.Role            = args.Role;
        this.PasswordHash    = args.PasswordHash;
        this.IsEmailVerified = args.IsEmailVerified;
        this.FirstLoginAt    = args.FirstLoginAt;
        this.CreatedAt       = args.CreatedAt;
        this.UpdatedAt       = args.UpdatedAt;
        this.Status          = args.Status;
    }
    public static IResult<User> From(UserConstructorArgs args) {
        var uniqueName = args.UniqueName?.Trim();
        if (string.IsNullOrWhiteSpace(uniqueName)) {
            uniqueName = null;
        }

        if (uniqueName is not null) {
            if (uniqueName.Length < 3) return Result.Failure<User>(DomainError.User.UniqueNameTooShort);
            if (uniqueName.Length > 50) return Result.Failure<User>(DomainError.User.UniqueNameTooLong);
        }

        if (string.IsNullOrWhiteSpace(args.PasswordHash)) return Result.Failure<User>(DomainError.Auth.PasswordCannotBeEmpty);

        return Result.Success(new User(args with {
            UniqueName = uniqueName,
        }));
    }
    #endregion

    #region Methods: Update Properties
    public IResult UpdatePasswordHash(string passwordHash) {
        if (string.IsNullOrWhiteSpace(passwordHash)) return Result.Failure(DomainError.Auth.PasswordCannotBeEmpty);
        this.PasswordHash = passwordHash;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult UpdateStatus(UserStatus status) {
        this.Status = status;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult UpdateRole(UserRole role) {
        this.Role = role;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult UpdateEmailAddress(EmailAddress emailAddress) {
        this.EmailAddress = emailAddress;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult UpdateIsEmailVerified(bool isEmailVerified) {
        this.IsEmailVerified = isEmailVerified;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult UpdateUniqueName(string uniqueName) {
        var normalizedUniqueName = uniqueName.Trim();
        if (normalizedUniqueName.Length < 3) return Result.Failure(DomainError.User.UniqueNameTooShort);
        if (normalizedUniqueName.Length > 50) return Result.Failure(DomainError.User.UniqueNameTooLong);
        this.UniqueName = normalizedUniqueName;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult MarkFirstLogin(DateTime firstLoginAt) {
        if (this.FirstLoginAt is not null) {
            return Result.Success();
        }

        this.FirstLoginAt = DateTime.SpecifyKind(firstLoginAt, DateTimeKind.Utc);
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    #endregion
}
