using Sandlada.Extension.Auth.Domain.Commons;
using Sandlada.Extension.Auth.Domain.Primitives;
using Sandlada.Extension.Auth.Domain.ValueObjects;

namespace Sandlada.Extension.Auth.Domain.Aggregates;

public sealed record UserProfileConstructorArgs {
    public required Guid Id { get; init; }
    public required Guid UserId { get; init; }
    public required DateTime CreatedAt { get; init; }
    public required DateTime UpdatedAt { get; init; }
    public uint SourceColorArgb { get; init; }                          = 0xFF0078D4;
    public bool IsDarkMode { get; init; }                               = false;
    public MaterialContrastLevel ContrastLevel { get; init; }           = MaterialContrastLevel.Default;
    public MaterialVariant Variant { get; init; }                       = MaterialVariant.Neutral;
    public string? DisplayName { get; init; }                           = default;
    public Gender Gender { get; init; }                                 = ValueObjects.Gender.Unknown;
    public string? PreferredLanguage { get; init; }                     = default;
    public string? Metadata { get; init; }                              = default;
}

public sealed class UserProfile : IAggregate<Guid> {

    #region Properties

    #region Base

    /// <summary>
    /// The Id is generated by the application and provided in the constructor arguments.
    /// It is not generated by the database.
    ///
    /// Both Id and UserId are required to uniquely identify a UserProfile.
    ///
    /// Id & UserId together are used as the composite primary key in the database, and UserId is also a foreign key referencing the Users table with a one-to-one relationship.
    /// </summary>
    public Guid Id { get; private set; }

    /// <summary>
    /// Id & UserId together are used as the composite primary key in the database, and UserId is also a foreign key referencing the Users table with a one-to-one relationship.
    /// </summary>
    public Guid UserId { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }
    #endregion

    #region Theme

    /// <summary>
    /// It is used to store @material/material-color-utilities HCT color in ARGB format (e.g. 0xFF0078D4 for the default blue color).
    /// </summary>
    public uint SourceColorArgb { get; private set; }
    public bool IsDarkMode { get; private set; }
    public MaterialContrastLevel ContrastLevel { get; private set; }

    /// <summary>
    /// It is used to determine the variant of the Material Design theme.
    /// </summary>
    public MaterialVariant Variant { get; private set; }
    #endregion

    #region Personalization

    /// <summary>
    /// The display name shown to other users. Can be changed by the user.
    /// </summary>
    public string? DisplayName { get; private set; }

    /// <summary>
    /// The user's gender identity.
    /// </summary>
    public Gender Gender { get; private set; }
    #endregion

    #region Response Style
    public string? PreferredLanguage { get; private set; }
    #endregion

    #region Metadata
    /// <summary>
    /// Opaque JSON metadata for third-party extensions.
    /// </summary>
    public string? Metadata { get; private set; }
    #endregion

    #endregion

    #region Constructors
    private UserProfile(UserProfileConstructorArgs args) {
        this.Id = args.Id;
        this.UserId = args.UserId;
        this.CreatedAt = args.CreatedAt;
        this.UpdatedAt = args.UpdatedAt;
        this.SourceColorArgb = args.SourceColorArgb;
        this.IsDarkMode = args.IsDarkMode;
        this.ContrastLevel = args.ContrastLevel;
        this.Variant = args.Variant;
        this.DisplayName = args.DisplayName;
        this.Gender = args.Gender;
        this.PreferredLanguage = args.PreferredLanguage;
        this.Metadata = args.Metadata;
    }
    public static IResult<UserProfile> From(UserProfileConstructorArgs args) {
        if (args is null) return Result.Failure<UserProfile>(DomainError.UserProfile.Invalid);
        return Result.Success(new UserProfile(args));
    }
    #endregion

    #region Methods: Update Properties
    public IResult UpdateSourceColorArgb(uint argb) {
        this.SourceColorArgb = argb;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateIsDarkMode(bool isDarkMode) {
        this.IsDarkMode = isDarkMode;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateContrastLevel(MaterialContrastLevel contrastLevel) {
        this.ContrastLevel = contrastLevel;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateVariant(MaterialVariant variant) {
        this.Variant = variant;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateDisplayName(string? displayName) {
        this.DisplayName = displayName;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateGender(Gender gender) {
        this.Gender = gender;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdatePreferredLanguage(string? preferredLanguage) {
        this.PreferredLanguage = preferredLanguage;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    public IResult UpdateMetadata(string? metadata) {
        this.Metadata = metadata;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }

    public IResult ResetToDefaults() {
        this.SourceColorArgb = 0xFF0078D4u;
        this.IsDarkMode = false;
        this.ContrastLevel = MaterialContrastLevel.Default;
        this.Variant = MaterialVariant.Neutral;
        this.DisplayName = null;
        this.Gender = ValueObjects.Gender.Unknown;
        this.PreferredLanguage = null;
        this.Metadata = null;
        this.UpdatedAt = DateTime.UtcNow;
        return Result.Success();
    }
    #endregion
}